python3 spider_main.py -n tb -k 兔子耳钉
python3 spider_main.py -n tb -k 兔子项链
python3 spider_main.py -n tb -k 兔子戒指
python3 spider_main.py -n tb -k 兔子耳环
python3 spider_main.py -n tb -k 兔子手链
python3 spider_main.py -n tb -k 兔子吊坠
python3 spider_main.py -n tb -k 桃子耳钉
python3 spider_main.py -n tb -k 桃子项链
python3 spider_main.py -n tb -k 桃子戒指
python3 spider_main.py -n tb -k 桃子耳环
python3 spider_main.py -n tb -k 桃子手链
python3 spider_main.py -n tb -k 桃子吊坠
